import type { Metadata } from 'next'
import Header from '@/components/Header'
import { roboto } from '../styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
